module.exports = [
  'Men\'s Basketball',
  'Women\'s Basketball',
  'Men\'s Baseball',
  'Women\'s Softball',
  'Men\'s Football',,
  'Men\'s Volleyball',
  'Women\'s Volleyball',
  'Men\'s Soccer',
  'Women\'s Soccer',
  'Men\'s Golf',
  'Women\'s Golf',
  'Men\'s Wrestling',
  'Men\'s Swimming',
  'Women\'s Swimming',
  'Men\'s Lacrosse',
  'Women\'s Lacrosse',
  'Men\'s Waterpolo',
  'Women\'s Waterpolo',
  'Men\'s Track',
  'Women\'s Track',
  'Men\'s Tennis',
  'Women\'s Tennis'
];
